language: node_js
node_js:
- 14.16.0
services:
- docker
cache: npm
script:
- docker build -t crwn-clothing .
- docker ps
- docker run --name crwn -d -it -p 80:80 crwn-clothing
deploy:
  provider: heroku
  api_key:
    secure: qr0JiISWMJ6X3ixzjdmQUDEubudea3uNSNEsbFTmJpF9zBFq2k4Ea6+HmAYG/OIBuHW0O7qkKFFDtHMEz+o2J6c/0ceBHIJrqDnjtXSo5s9V/Dbea4xcXkp1kIWrh1rLc5sWVdAWl++chQAgQXf3q5B/Dn3M4IwIlIaiHXVSPMOKetToRRrZbal3HOewYAebhGDZ1QKWpwkfRUmj0Gxl5T5dDPEBUf1Vhi4BcHQUwccMTtCk3wwnLLaux+dK21HfchvMyxAM0ucv5J27WvPxRZwMHJz+NrXrv3fxVVQEi1dyPr27dVO3oH5y3ifX8P6NnSprbNs8hzr9ULPlr7rcACIOg24I6ItCuQaVhytKFv6LCQkppUNkldGX6/QH2n9BznksxsfFbvkq24q0h5nuq8XD/hqIuyW+xorsMngE7V/hQE7UdE8Gld+VzZwZkyWjXKBaaMYx9oPWK3rndITm6XyNrtQcNA59sAxfF39SNTXSlqTkQnqomQ1ZPxHyS2EfvdqsW+nt0W1MedMFrynuHQRbrfkLKY0cCMXTwlKI/kj1WvBg00PKb7zo1839QYPyHMwGFjLY4p+1Acn0uIpQF/P40LNZknxZmkblm9vAGt6lC9guHAO3Y72xUdRJgA1evRToSHyW7UuNu0PuJIqtuUPGmzL1SxcoBeNhbpQBDWk=
  app: crwn-clothing
  on:
    repo: ashish314/crwn-clothing
  skip_cleanup: 'true'
