language: node_js
node_js: 
- 14.16.0

services:
- docker

cache: npm

script:
- docker build -t crwn-clothing .
- docker ps
- docker run --name crwn -d -it -p 80:80 crwn-clothing 

deploy:
  provider: heroku
  api_key:
    secure: "$heroku_token"
  app: "crwn-clothing314"
  on: "master"  
