sudo: required
language: node_js
node_js:
- 14.16.0
services:
- docker
cache: npm

before_install:
- docker build -t crwn-clothing .
- docker run -d -it -p 80:80 crwn-clothing

script:
- docker ps

deploy:
  provider: heroku
  api_key:
    secure: IimIovIBx3ifQSR4wYBJdg0oUOFWabEUo9X4KSxMK/GWsYwyG0sWkuRJ4m1TpxNuG1vC0Pn8K/GUsrSrr/cyrHroXAbDCehZGW8tkieJg7InLqfx8RCPZvl8A2tYWK/BvcfxCWCuj5W/+xYorjbwvy2F2eLNxN6l1eJ4YV7rsMeZOKCwLUN3bKzllxi8hQeTLhckWeJMf2fDB72NzqUWxeP4MB/oXKcVHVBskj+pDdSupY6MuReSeCHLxVG+p3Z8v4o1eK3LIOtxRMjPfvMuYqzOx2nECF4nIpUdM+2BNx6YHOeaVXaF1H4WzL2Uy7WNO/H05DOvYMrADLwn1gL22gPn8rf53Wy4jQVtS05lWZi68lVJE3wr6SxVyyQXOeT6SnMSHuk0Zbhk0dIVBZmhEQxgiqpq/1F2Csec/qEZKt6BEV0bUgm8H+AFFGLR1N/Yi/oUCTU/59WZn1WLMSRU+ysNLaTi3a9QdN+JhFU/Tw3YBwx+i9ErNigvAxwPwkvEeGP4rUhWk8dA71eBQEkxICYeEFsfhGzOv4WFOUPv4Flfo/cWURxxRtshvuglqDjf2+nuCvAy0/h26cQOId4+XGgiOBlfkJuRkL2LKxSEc2GyhSiBAe/Ahve7zKH+FUn5bDIhAAP66yPrGsr4rBMiJwJ1KsnPXOlRSqtYrE55Mm8=
  app: crwn-clothing314
  on: "master"
  skip_cleanup: 'false'
